---
deployment:
  tasks:
    - export DEPLOYPATH=/home4/tesorosd/public_html/biblioteca
    - /bin/cp -R Admin $DEPLOYPATH
    - /bin/cp -R Ajax $DEPLOYPATH
    - /bin/cp -R bibliotecaController $DEPLOYPATH
    - /bin/cp -R bibliotecaModel $DEPLOYPATH
    - /bin/cp -R bibliotecaTDDRespaldosBD $DEPLOYPATH
    - /bin/cp -R bibliotecaView $DEPLOYPATH
    - /bin/cp .gitignore $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp .env $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp composer.lock $DEPLOYPATH
